# 标题
site_name: 学习笔记
site_url: https://li624342713.github.io/paper/  # 必须与实际部署的完整路径一致
use_directory_urls: true  # 默认为 true，影响页面路径生成方式

# 索引
nav:
  - 论文阅读笔记:
      - 药物主题演化研究: read/药物主题演化研究/药物主题演化研究.md
      - 1. 知识网络耦合-科技关联: read/知识网络耦合-科技关联/知识网络耦合-科技关联.md
      - 2. 机器学习-技术机会识别: read/机器学习-技术机会识别/机器学习-技术机会识别.md
      - 3. 层次知识整合: read/层次知识整合/层次知识整合.md
      - 4. 科技层级联系的网络耦合方法: read/科技层级联系的网络耦合方法/科技层级联系的网络耦合方法.md
      - 5. 网络画像散度-科技关联: read/网络画像散度-科技关联/网络画像散度-科技关联.md
      - 6. 科技安全-新兴技术: read/科技安全-新兴技术/科技安全-新兴技术.md
      - 7. 科技关联: read/科技关联/科技关联.md
      - 8. 科技产创新驱动关系: read/科技产创新驱动关系/科技产创新驱动关系.md
      - 9. 要素依赖性与结构异质性: read/要素依赖性与结构异质性/要素依赖性与结构异质性.md
      - 10.突破性早期识别: read/突破性早期识别/突破性早期识别.md
      - 11.技术与前产业融合: read/技术与前产业融合/技术与前产业融合.md
      - 12.机会评价与优化: read/机会评价与优化/机会评价与优化.md
      - 13.生命周期-技术机会: read/生命周期-技术机会/生命周期-技术机会.md
      - 14.堆叠降噪自编码器( Sdae )技术组合: read/堆叠降噪自编码器( Sdae )技术组合/堆叠降噪自编码器( Sdae )技术组合.md
      - 15.监督学习-技术主题-技术融合: read/监督学习-技术主题-技术融合/监督学习-技术主题-技术融合.md
      - 16.相似性度量: read/相似性度量/相似性度量.md
      - 17.功能语义知识增强文本相似度: read/功能语义知识增强文本相似度/功能语义知识增强文本相似度.md
      - 18.链接预测和社区发现进行技术融合预测: read/链接预测和社区发现进行技术融合预测/链接预测和社区发现进行技术融合预测.md
      - 19.机器学习链接预测: read/机器学习链接预测/机器学习链接预测.md
      - 20.机器学习技术融合: read/机器学习技术融合/机器学习技术融合.md
      - 21.技术融合预测创新机会: read/技术融合预测创新机会/技术融合预测创新机会.md
      - 22.图卷积网络技术机会识别: read/图卷积网络技术机会识别/图卷积网络技术机会识别.md
      - 23.知识联系影响企业技术创新: read/知识联系影响企业技术创新/知识联系影响企业技术创新.md
      - 24.集成学习的颠覆性技术早期识别: read/集成学习的颠覆性技术早期识别/集成学习的颠覆性技术早期识别.md
      - 25.知识网络与链路预测: read/知识网络与链路预测/知识网络与链路预测.md
      - 26.技术发展趋势预测: read/技术发展趋势预测/技术发展趋势预测.md
      - 27.TO-RFM 模型: read/TO-RFM 模型/TO-RFM 模型.md
      - 28.聚类与多维空间: read/聚类与多维空间/聚类与多维空间.md
      - 29.主题挖掘与专利评估: read/主题挖掘与专利评估/主题挖掘与专利评估.md
      - 30.关键共性技术识别: read/关键共性技术识别/关键共性技术识别.md
      - 31.离群专利新兴技术识别: read/离群专利新兴技术识别/离群专利新兴技术识别.md
      - 32.技术知识流动预测: read/技术知识流动预测/技术知识流动预测.md
      - 33.知识跃迁路径: read/知识跃迁路径/知识跃迁路径.md
      - 34.潜在技术机会: read/潜在技术机会/潜在技术机会.md
      - 35.主题模型预测新兴技术: read/主题模型预测新兴技术/主题模型预测新兴技术.md
      - 36.科技关联演化分析: read/科技关联演化分析/科技关联演化分析.md
      - 37.链接预测机会识别: read/链接预测机会识别/链接预测机会识别.md
      - 38.过期专利中技术机会: read/过期专利中技术机会/过期专利中技术机会.md
      - 39.多技术融合: read/多技术融合/多技术融合.md
      - 40.机器学习结合技术路线图: read/机器学习结合技术路线图/机器学习结合技术路线图.md
      - 41.主题建模和SAO语义分析: read/主题建模和SAO语义分析/主题建模和SAO语义分析.md
      - 42.文本挖掘和F项分析: read/文本挖掘和F项分析/文本挖掘和F项分析.md
      - 43.新兴技术的早期识别: read/新兴技术的早期识别/新兴技术的早期识别.md
      - 44.科技互动: read/科技互动/科技互动.md
      - 45.科技差距: read/科技差距/科技差距.md
      - 46.生成式地形图绘制和链接预测: read/生成式地形图绘制和链接预测/生成式地形图绘制和链接预测.md
      - 47.论文与专利之间的文本相似度: read/论文与专利之间的文本相似度/论文与专利之间的文本相似度.md
      - 48.技术趋势预测科技差距: read/技术趋势预测科技差距/技术趋势预测科技差距.md
      - 49.BERT模型和语义分析: read/BERT模型和语义分析/BERT模型和语义分析.md
      - 50.科技中关联主题: read/科技中关联主题/科技中关联主题.md
      - 51.资金-科学-技术-创新关联分析: read/资金-科学-技术-创新关联分析/资金-科学-技术-创新关联分析.md
      - 52.技术关键词分析: read/技术关键词分析/技术关键词分析.md
      - 53.整合专利-产品数据库: read/整合专利-产品数据库/整合专利-产品数据库.md
      - 54.动态价值与多层网络: read/动态价值与多层网络/动态价值与多层网络.md
      - 55.潜在影响力预测: read/潜在影响力预测/潜在影响力预测.md














# 主题
theme:
  name: material
  features:
    - instant
    - navigation.tabs
    - navigation.sections

# 文本扩展
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true


# 额外的js
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js

# 额外的css
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css

# 额外的插件
extra:
  mathjax:
    tex:
      tags: 'ams'  # 启用 AMS 标签支持
      processEscapes: true

# 插件
plugins:
  - search